spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/soccer}
spring.datasource.username=${DATABASE_USER:soccer}
spring.datasource.password=${DATABASE_PASSWORD:soccer}
spring.sql.init.mode=always
game.config-dir=${GAME_CONFIG_DIR:../config}
server.port=8080
spring.jackson.serialization.order-map-entries-by-keys=true
spring.sql.init.separator=@@
